### ISSUE TITLE
How can I use batch size > 1?

### ISSUE THREAD

**Issue by TyroneLi** [happywu/Sequence-Level-Semantics-Aggregation#7]
When I try to use batch size greater than 1 for training, error occurs. If I want to change batch size bigger than 1, could you offer some advice how to modify code?Thx~

**Comment by happywu** [comment]
You need to modify the dataloader to provide data that has a batch size greater than 1.  You need to pad images to make them have the same size in order to form mini batch. 
And also the symbol file since there is some operation that assume the batch size is 1. You should do shape verify for the symbol file.
